Repository opencloud-eu/web-extensions, pull requests merged in 2025-04, with the labels that each got.

#87 create unique user for each test
  .woodpecker/e2e-tests.yaml
  package.json
  packages/web-app-draw-io/tests/e2e/createDrawIo.spec.ts
  packages/web-app-external-sites/tests/e2e/openExternalSite.spec.ts
  packages/web-app-json-viewer/tests/e2e/jsonViewer.spec.ts
  packages/web-app-unzip/tests/e2e/extractZip.spec.ts
  playwright.config.ts
  pnpm-lock.yaml
  support/helpers/api/apiHelper.ts
  support/helpers/api/getToken.ts
Labels: Type:DevOps, Type:Test

#88 ci: remove drone content since we use woodpecker now
  .drone.star
  .gitignore
  README.md
  support/drone/opencloud.web.config.json
Labels: Type:DevOps

#81 ci: build and release workflow
  .woodpecker/release.yaml
  packages/web-app-unzip/package.json
Labels: Type:DevOps

#91 ci: use woodpecker node image instead of a custom one
  .woodpecker/check-types.yaml
  .woodpecker/format.yaml
  .woodpecker/lint.yaml
  .woodpecker/unit-tests.yaml
Labels: Type:DevOps

#101 fix: docs url
  README.md
  packages/web-app-external-sites/README.md
Labels: Type:Bug, Type:Documentation
